import './globals.css'
import { Lexend } from 'next/font/google'

const lexend = Lexend({ subsets: ["latin"] as Array<'latin' | 'latin-ext' | 'vietnamese'>  })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${lexend.className}`}>{children}</body>
    </html>
  )
}
