name: Deploy to WordPress.org
on:
  push:
    branches:
      - own-plugin-release
    tags-ignore:
      - "*beta"
jobs:
  tag:
    name: New Release
    runs-on: ubuntu-latest
    #if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: 'Slack this'
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.