name: Publish to NPM

on:
  push:
    branches:
      - feat/titan-npm-publish

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        working-directory: includes/admin/page-optimizer
        run: npm install

      - name: Update Version
        working-directory: includes/admin/page-optimizer
        run: npm version patch

      - name: Build Project
        working-directory: includes/admin/page-optimizer
        run: npm run build

      - name: Publish to NPM
        working-directory: includes/admin/page-optimizer
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: npm publish

      - name: 'Slack this'
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.